#!/bin/bash

function createNsporg() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/nsporg.isp.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/nsporg.isp.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:6054 --caname ca-nsporg --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-nsporg.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-nsporg.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-nsporg.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-6054-ca-nsporg.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/nsporg.isp.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy nsporg's CA cert to nsporg's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/nsporg.isp.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/nsporg.isp.com/msp/tlscacerts/ca.crt"

  # Copy nsporg's CA cert to nsporg's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/nsporg.isp.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/nsporg.isp.com/tlsca/tlsca.nsporg.isp.com-cert.pem"

  # Copy nsporg's CA cert to nsporg's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/nsporg.isp.com/ca"
  cp "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/nsporg.isp.com/ca/ca.nsporg.isp.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-nsporg --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-nsporg --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-nsporg --id.name nsporgadmin --id.secret nsporgadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:6054 --caname ca-nsporg -M "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/nsporg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:6054 --caname ca-nsporg -M "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls" --enrollment.profile tls --csr.hosts peer0.nsporg.isp.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/nsporg.isp.com/peers/peer0.nsporg.isp.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:6054 --caname ca-nsporg -M "${PWD}/organizations/peerOrganizations/nsporg.isp.com/users/User1@nsporg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/nsporg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/nsporg.isp.com/users/User1@nsporg.isp.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://nsporgadmin:nsporgadminpw@localhost:6054 --caname ca-nsporg -M "${PWD}/organizations/peerOrganizations/nsporg.isp.com/users/Admin@nsporg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/nsporg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/nsporg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/nsporg.isp.com/users/Admin@nsporg.isp.com/msp/config.yaml"
}

function createEiorg() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/eiorg.isp.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/eiorg.isp.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-eiorg --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eiorg.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eiorg.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eiorg.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-eiorg.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/eiorg.isp.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy eiorg's CA cert to eiorg's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/eiorg.isp.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/eiorg.isp.com/msp/tlscacerts/ca.crt"

  # Copy eiorg's CA cert to eiorg's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/eiorg.isp.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/eiorg.isp.com/tlsca/tlsca.eiorg.isp.com-cert.pem"

  # Copy eiorg's CA cert to eiorg's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/eiorg.isp.com/ca"
  cp "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/eiorg.isp.com/ca/ca.eiorg.isp.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-eiorg --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-eiorg --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-eiorg --id.name eiorgadmin --id.secret eiorgadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-eiorg -M "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/eiorg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-eiorg -M "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls" --enrollment.profile tls --csr.hosts peer0.eiorg.isp.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/eiorg.isp.com/peers/peer0.eiorg.isp.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-eiorg -M "${PWD}/organizations/peerOrganizations/eiorg.isp.com/users/User1@eiorg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/eiorg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/eiorg.isp.com/users/User1@eiorg.isp.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://eiorgadmin:eiorgadminpw@localhost:7054 --caname ca-eiorg -M "${PWD}/organizations/peerOrganizations/eiorg.isp.com/users/Admin@eiorg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/eiorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/eiorg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/eiorg.isp.com/users/Admin@eiorg.isp.com/msp/config.yaml"
}

function createSchorg() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/schorg.isp.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/schorg.isp.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-schorg --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-schorg.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-schorg.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-schorg.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-schorg.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/schorg.isp.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy schorg's CA cert to schorg's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/schorg.isp.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/schorg.isp.com/msp/tlscacerts/ca.crt"

  # Copy schorg's CA cert to schorg's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/schorg.isp.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/schorg.isp.com/tlsca/tlsca.schorg.isp.com-cert.pem"

  # Copy schorg's CA cert to schorg's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/schorg.isp.com/ca"
  cp "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/schorg.isp.com/ca/ca.schorg.isp.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-schorg --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-schorg --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-schorg --id.name schorgadmin --id.secret schorgadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-schorg -M "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/schorg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-schorg -M "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls" --enrollment.profile tls --csr.hosts peer0.schorg.isp.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/schorg.isp.com/peers/peer0.schorg.isp.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-schorg -M "${PWD}/organizations/peerOrganizations/schorg.isp.com/users/User1@schorg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/schorg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/schorg.isp.com/users/User1@schorg.isp.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://schorgadmin:schorgadminpw@localhost:8054 --caname ca-schorg -M "${PWD}/organizations/peerOrganizations/schorg.isp.com/users/Admin@schorg.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/schorg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/schorg.isp.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/schorg.isp.com/users/Admin@schorg.isp.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/isp.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/isp.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/isp.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/isp.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/isp.com/msp/tlscacerts/tlsca.isp.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/isp.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/isp.com/tlsca/tlsca.isp.com-cert.pem"

# Loop through each orderer (orderer, orderer2, orderer3, orderer4) to register and generate artifacts
  for ORDERER in orderer orderer2 orderer3 orderer4; do
    echo "Registering ${ORDERER}"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name ${ORDERER} --id.secret ${ORDERER}pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo "Generating the ${ORDERER} MSP"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/isp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/msp/config.yaml"

    # Workaround: Rename the signcert file to ensure consistency with Cryptogen generated artifacts
    mv "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/msp/signcerts/cert.pem" "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/msp/signcerts/${ORDERER}.isp.com-cert.pem"

    echo "Generating the ${ORDERER} TLS certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls" --enrollment.profile tls --csr.hosts ${ORDERER}.isp.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/isp.com/orderers/${ORDERER}.isp.com/msp/tlscacerts/tlsca.isp.com-cert.pem"
  done

  # Register and generate artifacts for the orderer admin
  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/isp.com/users/Admin@isp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/isp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/isp.com/users/Admin@isp.com/msp/config.yaml"
}

createNsporg
createEiorg
createSchorg
createOrderer